# Generated by Django 2.1.7 on 2019-04-20 12:39

import api.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.users.models.UserManager()),
            ],
        ),
    ]
